### ISSUE TITLE
file explorer: reloading component again creates duplicate watcher

### ISSUE THREAD

**Issue by technoweenie** [manifold/tractor#79]
1. Create object
2. Add file explorer component.
3. Add `/tmp` path
4. Click "Refresh" on the object
5. Click "Reload" on the component

```
@dev   | panic: error: watcher is already running
@dev   |
@dev   | goroutine 124 [running]:
@dev   | github.com/manifold/tractor/pkg/stdlib/file.(*Explorer).ComponentEnable.func1(0xc0001a0960)
@dev   | 	/Users/rick/p/tractor/pkg/stdlib/file/explorer.go:84 +0x87
@dev   | created by github.com/manifold/tractor/pkg/stdlib/file.(*Explorer).ComponentEnable
@dev   | 	/Users/rick/p/tractor/pkg/stdlib/file/explorer.go:81 +0xe5
```

**Comment by progrium** [comment]
Great find
